### PR TITLE
feat: register/login with auth token

### PR DESCRIPTION
**Pull request by rdbishop19**
# Description

Authentication setup for Register/Login API endpoints

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Testing Instructions

```
git fetch --all
git checkout rb-authentication
python manage.py makemigrations
python manage.py migrate
```

1. Make sure after your migrate step that you had migrations applied related to `authuser`
2. Open up your browser and go to `http://127.0.0.1:8000/` and make sure the interactive API opens
3. Open Postman and try registering Tom Hanks to the `http://127.0.0.1:8000/register/` endpoint
```
{
    "username": "thanksWilson",
    "email": "tom@hanks.com",
    "password": "p@$$word!",
    "first_name": "Tom",
    "last_name": "Hanks"
}
```
^^JSON body
Headers: `Content-type: application/json`
4. Make sure you get back a valid token. Copy this token value for the next testing step
5. Check the `http://127.0.0.1:8000/login/` endpoint to get back Tom Hanks' valid login
```
{
    "username": "thanksWilson",
    "password": "p@$$word!"
}
```
^^JSON body
Headers: `Content-type: application/json; Authorization: Token [paste token here]`
6. Check that you get a JSON-object back with a `Valid: true` key included with the token

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by cherkesky — DISMISSED** [review]
shwifty!

**Review by cherkesky — APPROVED** [review]
shwifty!

**Review by sophiahoffman — APPROVED** [review]
yay

**Review by melliemuse — APPROVED** [review]
Works great - really helpful testing instructions!

**Pull request merged**
