### PR TITLE
added code to filter product list by product type

### PR DESCRIPTION
**Pull request by melliemuse**
When querying database for products, you can now filter by product id so only products of that type appear

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Testing Instructions

git fetch --all
git checkout ms-view-product-by-type

1. Type http://localhost:8000/products?category=1 into postman, make sure it only returns products with product_type_id of 1
2. Create a product with product id of 2 in Tableplus, DBeaver or Postman
3. Type http://localhost:8000/products?category=1 into postman, make sure it only returns products with product_type_id of 2
4. Make sure product query with limit still works

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by rdbishop19 — DISMISSED** [review]
Kewl 😎

**Review by klboyd — DISMISSED** [review]
Snazzy

**Review by klboyd — APPROVED** [review]
Snazzy pt 2

**Review by rdbishop19 — APPROVED** [review]
superkewl 🥇

**Pull request merged**
