### PR TITLE
Jwo orders view

### PR DESCRIPTION
**Pull request by jesieOldenburg**
# Description

Created orders view and added the url routes and imports to the view folder's `__init__.py` file.

Fixes # N/A

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

## Testing Instructions

Once added as a reviewer, click the checkout locally button above and run the commands on your local machine.

1. Open a new `GET` request in postman and grab a list of all orders with the following query: `http://localhost:3000/orders`.
_Return Value:_
```json
[    
  {
        "id": 1,
        "url": "http://localhost:8000/orders/1",
        "payment_type_id": 1,
        "created_at": "2019-09-23T14:06:30.047000Z"
    }
]
```
2. Now, make a request to the following url: `http://localhost:8000/orders/1`
_Return Value:_
```json
    {
        "id": 1,
        "url": "http://localhost:8000/orders/1",
        "payment_type_id": 1,
        "created_at": "2019-09-23T14:06:30.047000Z"
    }
```
## Next Steps
* Implement the `PUT` and `DEL` Methods for orders.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings or errors
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by cherkesky — DISMISSED** [review]

**Review by rdbishop19 — DISMISSED** [review]
GETs work as expected. 👍

**Comment by jesieOldenburg** [comment]
@rdbishop19 All merge conflicts resolved and ready for review! 🤘

**Review by sophiahoffman — APPROVED** [review]
looks good for get

**Review by melliemuse — APPROVED** [review]
Looks good! 👍

**Pull request merged**
